/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>

using namespace std;

int main()
{
	int accumulator = 0 ;
	
	for(int low = 1, high = 1, sum = 0 ; high <= 4000000 ;)
	{
		sum = low+high;
		low = high;
		high = sum;
		
		if(sum % 2 == 0)
		{
			accumulator += sum;
		}
	}
	
	cout << accumulator << endl;
}
